#19 Respect query parameters in redirect URL after login
cloudogu/sonar-cas-plugin pull request #20
Opened 2019-03-12 10:12 UTC by ppxl

If a logged-out user dials a sonar URL with query parameters (f. i. to
jump directly to an existing project with its name) that query
parameters are not kept, only the URL part. This defect occurs during
a first-time login as well as during a re-login.

This commit keeps all originally provided query parameters so after
login the user can be redirected to the desired resource without much
ado.

The added test DOES NOT reflect a direct cookie test because
`javax.servlet.http.Cookie` does not implement `equals` and `hashcode`.
Instead only by implication of the number of invocations we can know
it was probably called. (It IS call though, just check the debugger).

Since the cookie creation missed the context path (necessary for proper
deletion) the whole creation was refactored into a builder.

Furthermore, `LogoutHandler.handleInvalidJwtCookie()` did more than it
should. It is supposed to handle JWT cookie creation but redirected also
to a different URL if necessary. This redirection was pulled up into the
`ForceCasLoginFilter` so there's now a better balance and similarity
with similar code.

Resolves #19

2019-03-12 14:01 UTC, robertauer commented
Works in SonarQube, LGTM.

2019-03-12 14:46 UTC, sdorra requested changes

2019-03-12 14:46 UTC, sdorra commented on src/main/java/org/sonar/plugins/cas/util/CookieUtil.java
>  public final class CookieUtil {
I suggest to rename the class to "Cookies".

2019-03-12 14:46 UTC, sdorra commented on src/main/java/org/sonar/plugins/cas/util/CookieUtil.java
>  public final class CookieUtil {
Util classes should always have a private constructor.

2019-03-12 14:46 UTC, sdorra commented on src/main/java/org/sonar/plugins/cas/util/HttpUtil.java
> +            url += queryDelimiter + request.getQueryString();
The "queryDelimiter" could be inlined.

2019-03-12 14:46 UTC, sdorra commented on src/main/java/org/sonar/plugins/cas/ForceCasLoginFilter.java
> +        int maxRedirectCookieAge = SonarCasProperties.URL_AFTER_CAS_REDIRECT_COOKIE_MAX_AGE_IN_SECS.mustGetInteger(configuration);
Is the user forced to configure this? Could we not provide a sane default?

2019-03-12 14:50 UTC, sdorra requested changes

2019-03-12 14:50 UTC, sdorra commented on src/main/java/org/sonar/plugins/cas/ForceCasLoginFilter.java
> +        int maxRedirectCookieAge = SonarCasProperties.URL_AFTER_CAS_REDIRECT_COOKIE_MAX_AGE_IN_SECS.mustGetInteger(configuration);
It the user forced to configure this? Could we not provide a sane default?

2019-03-13 08:14 UTC, sdorra approved these changes

2019-03-13 08:14 UTC, merged